# Generated by Django 2.0.8 on 2018-12-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='article_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=300)),
                ('descs', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='article',
        ),
    ]
